-- ============================================================================
-- JobSync — Consolidated database schema
-- ============================================================================
-- Generated by reading through sqlscripts/000-046 in order and resolving every
-- later "fix" script against the ones it supersedes, cross-checked against a
-- live introspection dump of the production database for exact column types.
-- Includes the org-scoping fix from sqlscripts/049 for job_sheets and
-- alert_recipients admin visibility.
--
-- Run in: Supabase SQL Editor, on a fresh project, in one go.
-- ============================================================================

-- ── Extensions ────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto;

-- ── Tables ────────────────────────────────────────────────────────────────────

create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  full_name    text not null,
  email        text not null,
  phone        text,
  role         text not null check (role in ('admin', 'technician')),
  is_active    boolean not null default true,
  avatar_url   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  display_name text,
  gender       text check (gender in ('male', 'female', 'other', 'prefer_not_to_say')),
  country      text,
  preferences  jsonb not null default '{}'
);

create table public.organizations (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  owner_id   uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.organization_members (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  role            text not null check (role in ('admin', 'manager', 'technician')),
  added_by        uuid references public.profiles(id) on delete set null,
  joined_at       timestamptz not null default now(),
  is_active       boolean not null default true,
  unique (organization_id, user_id)
);

create table public.organization_invitations (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email           text not null,
  role            text not null default 'technician' check (role in ('admin', 'manager', 'technician')),
  invited_by      uuid not null references public.profiles(id) on delete cascade,
  status          text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at      timestamptz not null default now(),
  unique (organization_id, email)
);

create table public.job_orders (
  id                 uuid primary key default gen_random_uuid(),
  title              text not null,
  description        text not null,
  customer_name      text not null,
  customer_phone     text,
  location           text not null,
  priority           text not null check (priority in ('low', 'medium', 'high', 'urgent')),
  status             text not null default 'pending' check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  scheduled_date     date,
  scheduled_time     time,
  created_by         uuid not null references public.profiles(id),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  customer_email     text,
  job_type           text check (job_type in ('service', 'inspection', 'installation', 'maintenance', 'emergency', 'scheduled_maintenance', 'other')),
  job_type_other     text,
  location_street    text,
  location_city      text,
  location_state     text,
  location_postcode  text,
  due_date           date,
  billing_address    text,
  organization_id    uuid references public.organizations(id) on delete cascade
);

create index if not exists idx_job_orders_organization_id on public.job_orders(organization_id);

create table public.job_assignments (
  id             uuid primary key default gen_random_uuid(),
  job_order_id   uuid not null references public.job_orders(id) on delete cascade,
  technician_id  uuid not null references public.profiles(id) on delete cascade,
  assigned_at    timestamptz not null default now()
);

create table public.job_sheets (
  id                            uuid primary key default gen_random_uuid(),
  job_order_id                  uuid references public.job_orders(id) on delete cascade,
  technician_id                 uuid not null references public.profiles(id),
  work_performed                text not null,
  time_spent_minutes            integer not null,
  notes                         text,
  customer_signature_url        text,
  submitted_at                  timestamptz not null default now(),
  created_at                    timestamptz not null default now(),
  organization_id               uuid references public.organizations(id) on delete set null,
  sheet_number                  integer,
  job_title                     text,
  customer_name                 text,
  customer_phone                text,
  customer_email                text,
  job_location                  text,
  job_description               text,
  job_type                      text,
  job_date                      date,
  time_in                       time,
  time_out                      time,
  service_description           text,
  total_amount                  numeric(10, 2),
  technician_signature_url      text,
  additional_technician_names   text[]
);

create table public.attachments (
  id             uuid primary key default gen_random_uuid(),
  job_sheet_id   uuid not null references public.job_sheets(id) on delete cascade,
  storage_path   text not null,
  file_name      text not null,
  file_size      integer,
  mime_type      text,
  uploaded_at    timestamptz not null default now()
);

create table public.alerts (
  id               uuid primary key default gen_random_uuid(),
  title            text not null,
  message          text not null,
  created_by       uuid not null references public.profiles(id),
  created_at       timestamptz not null default now(),
  organization_id  uuid references public.organizations(id) on delete cascade
);

create index if not exists idx_alerts_organization_id on public.alerts(organization_id);

create table public.alert_recipients (
  id             uuid primary key default gen_random_uuid(),
  alert_id       uuid not null references public.alerts(id) on delete cascade,
  recipient_id   uuid not null references public.profiles(id) on delete cascade,
  read_at        timestamptz,
  created_at     timestamptz not null default now()
);

create table public.alert_jobs (
  id             uuid primary key default gen_random_uuid(),
  alert_id       uuid not null references public.alerts(id) on delete cascade,
  job_order_id   uuid not null references public.job_orders(id) on delete cascade,
  created_at     timestamptz not null default now(),
  unique (alert_id, job_order_id)
);

create table public.linked_emails (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  email       text not null,
  label       text,
  created_at  timestamptz not null default now(),
  unique (user_id, email)
);

create table public.org_sheet_counters (
  organization_id  uuid primary key references public.organizations(id) on delete cascade,
  last_number      integer not null default 0,
  updated_at       timestamptz not null default now()
);

create table public.login_history (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.profiles(id) on delete cascade,
  device_info     text not null,
  is_new_device   boolean not null default false,
  signed_in_at    timestamptz not null default now(),
  is_active       boolean not null default false
);

create index if not exists login_history_user_id_idx on public.login_history(user_id);

-- ── Functions ─────────────────────────────────────────────────────────────────

create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Final version (015) — explicit public. prefix + empty search_path, required
-- for SECURITY DEFINER functions on newer Supabase projects.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'role', 'technician')
  );
  return new;
end;
$$;

create or replace function public.create_staff_account(
  p_email     text,
  p_password  text,
  p_full_name text,
  p_role      text,
  p_phone     text default null
)
returns uuid
language plpgsql
security definer
set search_path = auth, public
as $$
declare
  v_user_id uuid;
begin
  if not exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  ) then
    raise exception 'Permission denied: caller is not an admin';
  end if;

  if p_role not in ('admin', 'technician') then
    raise exception 'Invalid role: must be admin or technician';
  end if;

  if exists (select 1 from auth.users where email = p_email) then
    raise exception 'A user with this email already exists';
  end if;

  v_user_id := gen_random_uuid();

  insert into auth.users (
    id, instance_id, aud, role, email, encrypted_password,
    email_confirmed_at, raw_user_meta_data, created_at, updated_at
  )
  values (
    v_user_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
    p_email, crypt(p_password, gen_salt('bf')), now(),
    jsonb_build_object('full_name', p_full_name, 'role', p_role), now(), now()
  );

  if p_phone is not null and p_phone <> '' then
    update public.profiles set phone = p_phone where id = v_user_id;
  end if;

  return v_user_id;
end;
$$;

grant execute on function public.create_staff_account(text, text, text, text, text) to authenticated;

-- SECURITY DEFINER helper used by organization_members policies to avoid
-- infinite recursion (a policy that queries its own table via a normal
-- subquery re-triggers RLS on itself).
create or replace function public.is_org_admin_or_manager(org_id uuid)
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1 from public.organization_members
    where organization_id = org_id
      and user_id = auth.uid()
      and role in ('admin', 'manager')
  )
$$;

create or replace function public.is_org_member(org_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.organization_members
    where organization_id = org_id
      and user_id = auth.uid()
  )
$$;

create or replace function public.create_organization(org_name text)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_org     public.organizations;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if length(trim(org_name)) < 2 then
    raise exception 'Organization name must be at least 2 characters';
  end if;

  insert into public.organizations (name, owner_id)
  values (trim(org_name), v_user_id)
  returning * into v_org;

  insert into public.organization_members (organization_id, user_id, role, added_by)
  values (v_org.id, v_user_id, 'admin', v_user_id);

  return row_to_json(v_org);
end;
$$;

grant execute on function public.create_organization(text) to authenticated;

-- Final version (032) — explicit search_path so auth.uid() and table refs
-- resolve correctly.
create or replace function public.accept_organization_invitation(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_inv record;
begin
  select * into v_inv
  from public.organization_invitations
  where id = p_invitation_id
    and lower(email) = lower(
      (select email from public.profiles where id = auth.uid())
    )
    and status = 'pending';

  if not found then
    raise exception 'Invitation not found or already responded to.';
  end if;

  insert into public.organization_members (organization_id, user_id, role, added_by)
  values (v_inv.organization_id, auth.uid(), v_inv.role, v_inv.invited_by)
  on conflict (organization_id, user_id) do nothing;

  update public.organization_invitations
  set status = 'accepted'
  where id = p_invitation_id;
end;
$$;

create or replace function public.peek_next_sheet_number(p_org_id uuid)
returns integer
language plpgsql
security definer
as $$
declare
  v_last integer;
begin
  select last_number into v_last
  from public.org_sheet_counters
  where organization_id = p_org_id;

  if v_last is null then
    return 1;
  end if;
  return v_last + 1;
end;
$$;

create or replace function public.claim_sheet_number(p_org_id uuid)
returns integer
language plpgsql
security definer
as $$
declare
  v_claimed integer;
begin
  insert into public.org_sheet_counters (organization_id, last_number, updated_at)
  values (p_org_id, 1, now())
  on conflict (organization_id) do update
    set last_number = public.org_sheet_counters.last_number + 1,
        updated_at  = now()
  returning last_number into v_claimed;

  return v_claimed;
end;
$$;

create or replace function public.delete_user_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid      uuid := auth.uid();
  v_org_ids  uuid[];
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  -- Orgs where this user is the SOLE admin get fully deleted; orgs with other
  -- admins are left intact.
  select array_agg(om.organization_id) into v_org_ids
  from public.organization_members om
  where om.user_id = v_uid
    and om.role    = 'admin'
    and not exists (
      select 1 from public.organization_members om2
      where om2.organization_id = om.organization_id
        and om2.role            = 'admin'
        and om2.user_id        != v_uid
    );

  if v_org_ids is not null and array_length(v_org_ids, 1) > 0 then
    delete from public.alert_recipients
    where alert_id in (select id from public.alerts where organization_id = any(v_org_ids));

    delete from public.alerts where organization_id = any(v_org_ids);

    delete from public.attachments
    where job_sheet_id in (select js.id from public.job_sheets js where js.organization_id = any(v_org_ids));

    delete from public.job_sheets where organization_id = any(v_org_ids);

    delete from public.attachments
    where job_sheet_id in (
      select js.id from public.job_sheets js
      join public.job_orders jo on jo.id = js.job_order_id
      where jo.organization_id = any(v_org_ids)
    );
    delete from public.job_sheets
    where job_order_id in (select id from public.job_orders where organization_id = any(v_org_ids));

    delete from public.job_assignments
    where job_order_id in (select id from public.job_orders where organization_id = any(v_org_ids));

    delete from public.job_orders where organization_id = any(v_org_ids);
    delete from public.org_sheet_counters where organization_id = any(v_org_ids);
    delete from public.organization_invitations where organization_id = any(v_org_ids);
    delete from public.organization_members where organization_id = any(v_org_ids);
    delete from public.organizations where id = any(v_org_ids);
  end if;

  delete from public.organization_members where user_id = v_uid;

  delete from public.organization_invitations
  where invited_by = v_uid
     or lower(email) = lower((select email from public.profiles where id = v_uid));

  delete from auth.users where id = v_uid;
end;
$$;

grant execute on function public.delete_user_account() to authenticated;

-- Final version (042) — tracks is_active per device row.
create or replace function public.record_sign_in(p_device_info text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_is_new  boolean;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select not exists (
    select 1 from public.login_history
    where user_id = v_user_id and device_info = p_device_info
  ) into v_is_new;

  update public.login_history
    set is_active = false
  where user_id = v_user_id and device_info = p_device_info;

  insert into public.login_history (user_id, device_info, is_new_device, is_active)
  values (v_user_id, p_device_info, v_is_new, true);

  delete from public.login_history
  where user_id = v_user_id
    and id not in (
      select id from public.login_history
      where user_id = v_user_id
      order by signed_in_at desc
      limit 20
    );

  return v_is_new;
end;
$$;

grant execute on function public.record_sign_in(text) to authenticated;

create or replace function public.claim_open_job(p_job_id uuid)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
  v_count  int;
begin
  select status into v_status
  from public.job_orders
  where id = p_job_id
  for update;

  if not found then
    return json_build_object('success', false, 'error', 'Job not found');
  end if;

  if v_status <> 'pending' then
    return json_build_object('success', false, 'error', 'This job is no longer available');
  end if;

  select count(*) into v_count
  from public.job_assignments
  where job_order_id = p_job_id;

  if v_count > 0 then
    return json_build_object('success', false, 'error', 'This job was just claimed by another technician');
  end if;

  insert into public.job_assignments (job_order_id, technician_id)
  values (p_job_id, auth.uid());

  update public.job_orders
  set status = 'in_progress', updated_at = now()
  where id = p_job_id;

  return json_build_object('success', true);
end;
$$;

-- SECURITY DEFINER so the "is this job unassigned" check in the open-jobs
-- RLS policy below isn't itself filtered by job_assignments RLS (which would
-- make jobs assigned to OTHER technicians look unassigned to everyone else).
create or replace function public.job_has_any_assignment(p_job_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.job_assignments
    where job_order_id = p_job_id
  );
$$;

-- ── Triggers ──────────────────────────────────────────────────────────────────

create trigger set_updated_at before update on public.job_orders
  for each row execute function public.handle_updated_at();

create trigger set_updated_at before update on public.profiles
  for each row execute function public.handle_updated_at();

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Row Level Security ───────────────────────────────────────────────────────

alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.organization_invitations enable row level security;
alter table public.job_orders enable row level security;
alter table public.job_assignments enable row level security;
alter table public.job_sheets enable row level security;
alter table public.attachments enable row level security;
alter table public.alerts enable row level security;
alter table public.alert_recipients enable row level security;
alter table public.alert_jobs enable row level security;
alter table public.linked_emails enable row level security;
alter table public.org_sheet_counters enable row level security;
alter table public.login_history enable row level security;

-- ── profiles ──────────────────────────────────────────────────────────────────

create policy "Profiles are viewable by authenticated users" on public.profiles
  for select using (auth.uid() is not null);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Admins can insert profiles" on public.profiles
  for insert with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Admins can update any profile" on public.profiles
  for update using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- ── organizations ─────────────────────────────────────────────────────────────

create policy "Members can view their organization" on public.organizations
  for select using (
    exists (
      select 1 from public.organization_members om
      where om.organization_id = organizations.id and om.user_id = auth.uid()
    )
  );

create policy "Authenticated users can create an organization" on public.organizations
  for insert with check (auth.uid() is not null and owner_id = auth.uid());

create policy "Owner can update organization" on public.organizations
  for update using (owner_id = auth.uid());

create policy "Owner can delete organization" on public.organizations
  for delete using (owner_id = auth.uid());

create policy "Invitees can view orgs they are invited to" on public.organizations
  for select using (
    exists (
      select 1 from public.organization_invitations oi
      where oi.organization_id = organizations.id
        and lower(oi.email) = lower((select email from public.profiles where id = auth.uid()))
        and oi.status = 'pending'
    )
  );

-- ── organization_members ──────────────────────────────────────────────────────

create policy "Members can view org roster" on public.organization_members
  for select using (public.is_org_member(organization_members.organization_id));

create policy "Members can view own memberships" on public.organization_members
  for select using (user_id = auth.uid() and is_active = true);

create policy "Admins and managers can add members" on public.organization_members
  for insert with check (
    (
      organization_members.user_id = auth.uid()
      and exists (
        select 1 from public.organizations o
        where o.id = organization_members.organization_id and o.owner_id = auth.uid()
      )
    )
    or public.is_org_admin_or_manager(organization_members.organization_id)
  );

create policy "Admins and managers can update member roles" on public.organization_members
  for update using (public.is_org_admin_or_manager(organization_members.organization_id));

create policy "Admins and managers can remove members" on public.organization_members
  for delete using (public.is_org_admin_or_manager(organization_members.organization_id));

create policy "Members can leave organization" on public.organization_members
  for delete using (user_id = auth.uid());

-- ── organization_invitations ─────────────────────────────────────────────────

create policy "Org admins view invitations" on public.organization_invitations
  for select using (
    exists (
      select 1 from public.organization_members
      where organization_id = organization_invitations.organization_id
        and user_id = auth.uid() and role in ('admin', 'manager')
    )
  );

create policy "Org admins create invitations" on public.organization_invitations
  for insert with check (
    invited_by = auth.uid()
    and exists (
      select 1 from public.organization_members
      where organization_id = organization_invitations.organization_id
        and user_id = auth.uid() and role in ('admin', 'manager')
    )
  );

create policy "Org admins delete invitations" on public.organization_invitations
  for delete using (
    exists (
      select 1 from public.organization_members
      where organization_id = organization_invitations.organization_id
        and user_id = auth.uid() and role in ('admin', 'manager')
    )
  );

create policy "Users see own invitations" on public.organization_invitations
  for select using (
    lower(email) = lower((select email from public.profiles where id = auth.uid()))
  );

create policy "Users respond to own invitations" on public.organization_invitations
  for update using (
    lower(email) = lower((select email from public.profiles where id = auth.uid()))
  )
  with check (
    lower(email) = lower((select email from public.profiles where id = auth.uid()))
    and status in ('accepted', 'rejected')
  );

-- ── job_orders ────────────────────────────────────────────────────────────────

create policy "org_admins_manage_job_orders" on public.job_orders
  using (
    exists (
      select 1 from public.organization_members om
      where om.user_id = auth.uid()
        and om.role in ('admin', 'manager')
        and om.organization_id = job_orders.organization_id
    )
  );

create policy "Technicians can update status of assigned job_orders" on public.job_orders
  for update using (
    exists (
      select 1 from public.job_assignments
      where job_order_id = job_orders.id and technician_id = auth.uid()
    )
  );

-- Final version (046): assigned OR open-and-claimable, via a SECURITY DEFINER
-- helper so the "unassigned" check isn't itself narrowed by job_assignments RLS.
create policy "Technicians see assigned or open job_orders" on public.job_orders
  for select using (
    exists (
      select 1 from public.job_assignments
      where job_order_id = job_orders.id and technician_id = auth.uid()
    )
    or (
      job_orders.status = 'pending'
      and not public.job_has_any_assignment(job_orders.id)
      and exists (
        select 1 from public.organization_members
        where organization_id = job_orders.organization_id and user_id = auth.uid()
      )
    )
  );

-- ── job_assignments ───────────────────────────────────────────────────────────

create policy "org_admins_manage_assignments" on public.job_assignments
  using (
    exists (
      select 1 from public.organization_members om
      where om.user_id = auth.uid() and om.role in ('admin', 'manager')
    )
  );

create policy "Technicians see own assignments" on public.job_assignments
  for select using (technician_id = auth.uid());

-- ── job_sheets ────────────────────────────────────────────────────────────────

create policy "Admins see all job_sheets" on public.job_sheets
  for select using (
    exists (
      select 1 from public.organization_members om
      where om.user_id = auth.uid()
        and om.role in ('admin', 'manager')
        and om.organization_id = job_sheets.organization_id
    )
  );

create policy "Technicians select own job_sheets" on public.job_sheets
  for select using (technician_id = auth.uid());

create policy "Technicians insert own job_sheets" on public.job_sheets
  for insert with check (technician_id = auth.uid());

create policy "Technicians update own job_sheets" on public.job_sheets
  for update using (technician_id = auth.uid());

create policy "Technicians delete own job_sheets" on public.job_sheets
  for delete using (technician_id = auth.uid());

-- ── attachments ───────────────────────────────────────────────────────────────

create policy "Attachments follow job sheet access" on public.attachments
  using (
    exists (
      select 1 from public.job_sheets js
      where js.id = attachments.job_sheet_id
        and (
          js.technician_id = auth.uid()
          or exists (
            select 1 from public.organization_members om
            where om.user_id = auth.uid() and om.role in ('admin', 'manager')
          )
        )
    )
  );

-- ── alerts ────────────────────────────────────────────────────────────────────

create policy "org_admins_manage_alerts" on public.alerts
  using (
    exists (
      select 1 from public.organization_members om
      where om.user_id = auth.uid()
        and om.role in ('admin', 'manager')
        and om.organization_id = alerts.organization_id
    )
  );

create policy "technicians_see_own_alerts" on public.alerts
  for select using (
    exists (
      select 1 from public.alert_recipients
      where alert_id = alerts.id and recipient_id = auth.uid()
    )
  );

-- ── alert_recipients ──────────────────────────────────────────────────────────

-- alert_recipients has no organization_id of its own, so scope through the
-- parent alert (same join pattern used by alert_jobs' admin policy below).
create policy "Admins manage alert_recipients" on public.alert_recipients
  using (
    exists (
      select 1 from public.alerts a
      inner join public.organization_members om
              on om.organization_id = a.organization_id
             and om.user_id         = auth.uid()
             and om.role in ('admin', 'manager')
      where a.id = alert_recipients.alert_id
    )
  );

create policy "Technicians see own alert_recipients" on public.alert_recipients
  for select using (recipient_id = auth.uid());

create policy "Technicians update own read status" on public.alert_recipients
  for update using (recipient_id = auth.uid());

-- ── alert_jobs ────────────────────────────────────────────────────────────────

create policy "Org admins manage alert_jobs" on public.alert_jobs
  for all using (
    exists (
      select 1 from public.alerts a
      inner join public.organization_members om
              on om.organization_id = a.organization_id
             and om.user_id         = auth.uid()
             and om.role in ('owner', 'admin', 'manager')
      where a.id = alert_jobs.alert_id
    )
  );

create policy "Alert recipients view alert_jobs" on public.alert_jobs
  for select using (
    exists (
      select 1 from public.alert_recipients ar
      where ar.alert_id = alert_jobs.alert_id and ar.recipient_id = auth.uid()
    )
  );

-- ── linked_emails ─────────────────────────────────────────────────────────────

create policy "Users can view own linked_emails" on public.linked_emails
  for select using (user_id = auth.uid());

create policy "Users can insert own linked_emails" on public.linked_emails
  for insert with check (user_id = auth.uid());

create policy "Users can delete own linked_emails" on public.linked_emails
  for delete using (user_id = auth.uid());

-- ── org_sheet_counters ────────────────────────────────────────────────────────
-- No insert/update policies for regular users — writes only happen via the
-- SECURITY DEFINER claim_sheet_number() function above, which bypasses RLS.

create policy "Org members can read sheet counter" on public.org_sheet_counters
  for select using (
    exists (
      select 1 from public.organization_members
      where organization_id = org_sheet_counters.organization_id and user_id = auth.uid()
    )
  );

-- ── login_history ─────────────────────────────────────────────────────────────

create policy "Users can view own login history" on public.login_history
  for select using (auth.uid() = user_id);

create policy "Users can delete own login history" on public.login_history
  for delete using (auth.uid() = user_id);

create policy "Users can update own login history" on public.login_history
  for update using (auth.uid() = user_id);

-- ── Storage ───────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public)
values ('job-attachments', 'job-attachments', true)
on conflict (id) do nothing;

create policy "Authenticated users can upload job attachments"
on storage.objects for insert to authenticated
with check (bucket_id = 'job-attachments');

create policy "Authenticated users can view job attachments"
on storage.objects for select to authenticated
using (bucket_id = 'job-attachments');

create policy "Authenticated users can delete job attachments"
on storage.objects for delete to authenticated
using (bucket_id = 'job-attachments');
